services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO console port
    environment:
      MINIO_ROOT_USER: "minioadmin"     # Change this to your desired username
      MINIO_ROOT_PASSWORD: "minioadmin" # Change this to a strong password
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    
volumes:
  minio-data:
    driver: local
